<?php
/**
 * @file
 * dt_ct_actualites.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function dt_ct_actualites_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-actualites-field_all_sliders'
  $field_instances['node-actualites-field_all_sliders'] = array(
    'bundle' => 'actualites',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_all_sliders',
    'label' => 'Sliders',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 31,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Sliders');

  return $field_instances;
}
